# Generated by Django 4.0.3 on 2023-05-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0002_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
