# Generated by Django 4.2.2 on 2023-06-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='studentProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learnApp.profile'),
        ),
    ]
