# Generated by Django 4.2.2 on 2023-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0008_answers_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subject',
            field=models.CharField(default='student', max_length=255),
        ),
    ]
