# Generated by Django 4.2.2 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0009_useraccount_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
